In [1]:
import numpy as np

In [8]:
# Create a random vector of size 15 with integers in the range 1-20
vec = np.random.randint(1, 21, size=15)
print("Original Random vector:\n", vec)

#Reshape the array to 3 by 5
vec = vec.reshape(3, 5)
print("\nReshaped array (3x5):\n", vec)

# Print the shape of the array
print("\nArray shape:", vec.shape)

# Replace the max in each row by 0
row_max_indices = np.argmax(vec, axis=1)
for i in range(vec.shape[0]):
    vec[i, row_max_indices[i]] = 0

print("\nArray after replacing max in each row with 0:\n", vec)


Original Random vector:
 [ 8 17 19  6  3  7  3 14 11  8  3  2 10 12  2]

Reshaped array (3x5):
 [[ 8 17 19  6  3]
 [ 7  3 14 11  8]
 [ 3  2 10 12  2]]

Array shape: (3, 5)

Array after replacing max in each row with 0:
 [[ 8 17  0  6  3]
 [ 7  3  0 11  8]
 [ 3  2 10  0  2]]


In [6]:
# Creating a 4x3 2D array with 4-byte integers (int32)
array_TD = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]], dtype=np.int32)

# Prints the 2D array
print("2D Array:\n", array_TD)

# Prints the shape of the array
print("\nShape of array:", array_TD.shape)

# Prints the type of the array
print("Type of array:", type(array_TD))

# Prints the data type of the array elements
print("Data type of elements:", array_TD.dtype)


2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape of array: (4, 3)
Type of array: <class 'numpy.ndarray'>
Data type of elements: int32


In [5]:
# Defining the square matrix
matrix = np.array([[3, -2],
                   [1,  0]])

# Computing eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Display the results
print("Matrix:")
print(matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nRight Eigenvectors (columns):")
print(eigenvectors)


Matrix:
[[ 3 -2]
 [ 1  0]]

Eigenvalues:
[2. 1.]

Right Eigenvectors (columns):
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
# Defining the array
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Extracting the diagonal elements using np.diagonal()
diag_elements = np.diagonal(arr)

# Finding the sum of the diagonal elements
diag_sum = np.sum(diag_elements)

print("Array:")
print(arr)

print("\nDiagonal elements:", diag_elements)
print("Sum of diagonal elements:", diag_sum)


Array:
[[0 1 2]
 [3 4 5]]

Diagonal elements: [0 4]
Sum of diagonal elements: 4


In [3]:
# Original array of shape 3x2
array = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

# Reshapes the array to shape 2x3
New_array = array.reshape(2, 3)

print("Original array (3x2):")
print(array)

print("\nReshaped array (2x3):")
print(New_array)


Original array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
